version: "3.1"

services:

  # https://github.com/sameersbn/docker-redmine
  redmine:
    image: sameersbn/redmine:3.4.1
    restart: always
    ports:
      - 18080:80
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
      DB_ADAPTER: postgresql
      DB_HOST: db
      DB_NAME: redmine
      DB_USER: redmine
      DB_PASS: redmine
      NGINX_MAX_UPLOAD_SIZE: 20m
    volumes:
      - ./redmine/data:/home/redmine/data

  # https://hub.docker.com/_/postgres/
  db:
    image: postgres:9.6.3
    restart: always
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
    volumes:
      - ./redmine/pgdata:/var/lib/postgresql/data
